/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal_josegramage.Modulos.Menu.Vista;

import proyectofinal_josegramage.Librerias.Singletons;

/**
 *
 * @author Joso
 */

public class Vtna_Menu_Admin extends javax.swing.JFrame {

    public Vtna_Menu_Admin() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnClientesA = new javax.swing.JButton();
        btnConfigA = new javax.swing.JButton();
        btnProductosA = new javax.swing.JButton();
        btnJuegosA = new javax.swing.JButton();
        btnEstadA = new javax.swing.JButton();
        panelMenuAdmin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientesA.setText("Clientes");
        btnClientesA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientesA.setOpaque(false);
        panelMenu.add(btnClientesA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, 110, -1));

        btnConfigA.setText("Configuración");
        btnConfigA.setActionCommand("");
        btnConfigA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigA.setOpaque(false);
        btnConfigA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfigAMouseEntered(evt);
            }
        });
        panelMenu.add(btnConfigA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 110, -1));

        btnProductosA.setText("Productos");
        panelMenu.add(btnProductosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 110, -1));

        btnJuegosA.setText("Juegos");
        panelMenu.add(btnJuegosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 110, -1));

        btnEstadA.setText("Estadisticas");
        panelMenu.add(btnEstadA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 253, 110, -1));

        panelMenuAdmin.setVisible(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/fondos/img_menu_admin.jpg"))); // NOI18N

        javax.swing.GroupLayout panelMenuAdminLayout = new javax.swing.GroupLayout(panelMenuAdmin.getContentPane());
        panelMenuAdmin.getContentPane().setLayout(panelMenuAdminLayout);
        panelMenuAdminLayout.setHorizontalGroup(
            panelMenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        panelMenuAdminLayout.setVerticalGroup(
            panelMenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAdminLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMenu.add(panelMenuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 420, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfigAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigAMouseEntered
    //    Singletons.menu.btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/config2.png")));
             
    }//GEN-LAST:event_btnConfigAMouseEntered

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnClientesA;
    public static javax.swing.JButton btnConfigA;
    public static javax.swing.JButton btnEstadA;
    public static javax.swing.JButton btnJuegosA;
    public static javax.swing.JButton btnProductosA;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel panelMenu;
    public static javax.swing.JInternalFrame panelMenuAdmin;
    // End of variables declaration//GEN-END:variables
}
