/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal_josegramage.Modulos.Juegos.Vista;


/**
 *
 * @author Joso
 */
public class Vtna_jue_Modif extends javax.swing.JFrame {

    public Vtna_jue_Modif() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModif = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etiGuardadoM = new javax.swing.JLabel();
        etiEmailM = new javax.swing.JLabel();
        etiAvatarM = new javax.swing.JLabel();
        etiDireccionM = new javax.swing.JLabel();
        txtNombreM = new javax.swing.JTextField();
        txtCompanyiaM = new javax.swing.JTextField();
        btnAceptarM = new javax.swing.JButton();
        btnCancelarM = new javax.swing.JButton();
        errorNombreM = new javax.swing.JButton();
        errorCompanyiaM = new javax.swing.JButton();
        errorTipoM = new javax.swing.JButton();
        btnOKM = new javax.swing.JButton();
        btnVolverM = new javax.swing.JButton();
        errorDescripcionM = new javax.swing.JButton();
        btnCambiarImgM = new javax.swing.JButton();
        errorPrecioM = new javax.swing.JButton();
        txtTipoM = new javax.swing.JTextField();
        txtPrecioM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionM = new javax.swing.JTextArea();

        panelModif.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        panelModif.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setText("Companyia:");
        panelModif.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel4.setText("Tipo:");
        panelModif.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        etiGuardadoM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiGuardadoM.setForeground(new java.awt.Color(0, 204, 102));
        etiGuardadoM.setText("Juego modificado con éxito");
        panelModif.add(etiGuardadoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        etiEmailM.setText("Descripcion:");
        panelModif.add(etiEmailM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        etiAvatarM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelModif.add(etiAvatarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 90));

        etiDireccionM.setText("Precio:");
        panelModif.add(etiDireccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));
        panelModif.add(txtNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 129, -1));
        panelModif.add(txtCompanyiaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 129, -1));

        btnAceptarM.setText("Aceptar");
        panelModif.add(btnAceptarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btnCancelarM.setText("Cancelar");
        panelModif.add(btnCancelarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        errorNombreM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 22, 20));

        errorCompanyiaM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorCompanyiaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 22, 20));

        errorTipoM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorTipoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 22, 20));

        btnOKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/acierto.png"))); // NOI18N
        panelModif.add(btnOKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 30, 30));

        btnVolverM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolverM.setText("VOLVER");
        panelModif.add(btnVolverM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 100, -1));

        errorDescripcionM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorDescripcionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 22, 20));

        btnCambiarImgM.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnCambiarImgM.setText("cambiar imagen");
        panelModif.add(btnCambiarImgM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 125, 90, -1));

        errorPrecioM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorPrecioM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 22, 20));
        panelModif.add(txtTipoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 130, -1));
        panelModif.add(txtPrecioM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, -1));

        txtDescripcionM.setColumns(20);
        txtDescripcionM.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionM);

        panelModif.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAceptarM;
    public static javax.swing.JButton btnCambiarImgM;
    public static javax.swing.JButton btnCancelarM;
    public static javax.swing.JButton btnOKM;
    public static javax.swing.JButton btnVolverM;
    public static javax.swing.JButton errorCompanyiaM;
    public static javax.swing.JButton errorDescripcionM;
    public static javax.swing.JButton errorNombreM;
    public static javax.swing.JButton errorPrecioM;
    public static javax.swing.JButton errorTipoM;
    public static javax.swing.JLabel etiAvatarM;
    private javax.swing.JLabel etiDireccionM;
    private javax.swing.JLabel etiEmailM;
    public static javax.swing.JLabel etiGuardadoM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel panelModif;
    public static javax.swing.JTextField txtCompanyiaM;
    public static javax.swing.JTextArea txtDescripcionM;
    public static javax.swing.JTextField txtNombreM;
    public static javax.swing.JTextField txtPrecioM;
    public static javax.swing.JTextField txtTipoM;
    // End of variables declaration//GEN-END:variables
}
