/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal_josegramage.Modulos.Juegos.Vista;

/**
 *
 * @author Joso
 */
public class Vtna_jue_Crear extends javax.swing.JFrame {


    public Vtna_jue_Crear() {

        initComponents();
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCompanyia = new javax.swing.JTextField();
        txtRef = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        etiGuardado = new javax.swing.JLabel();
        etiEmail = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        errorPrecio = new javax.swing.JButton();
        etiPrecioError = new javax.swing.JLabel();
        etiAvatar = new javax.swing.JLabel();
        btnCargarImg = new javax.swing.JButton();
        etiEmail1 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        errorRef = new javax.swing.JButton();
        errorNombre = new javax.swing.JButton();
        errorCompanyia = new javax.swing.JButton();
        errorTipo = new javax.swing.JButton();
        errorDescripcion = new javax.swing.JButton();

        panelCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        panelCrear.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel2.setText("Companyia:");
        panelCrear.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel3.setText("Ref:");
        panelCrear.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel4.setText("Tipo:");
        panelCrear.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));
        panelCrear.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 129, -1));
        panelCrear.add(txtCompanyia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 129, -1));
        panelCrear.add(txtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 129, -1));

        btnAceptar.setText("Aceptar");
        panelCrear.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        btnCancelar.setText("Cancelar");
        panelCrear.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        etiGuardado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiGuardado.setForeground(new java.awt.Color(0, 204, 102));
        etiGuardado.setText("Juego guardado con éxito");
        panelCrear.add(etiGuardado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        etiEmail.setText("Precio:");
        panelCrear.add(etiEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/acierto.png"))); // NOI18N
        panelCrear.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 30, 30));

        btnNuevo.setText("Nuevo");
        panelCrear.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 110, 60));

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolver.setText("VOLVER");
        panelCrear.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 180, -1));

        errorPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelCrear.add(errorPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 22, 20));

        etiPrecioError.setForeground(new java.awt.Color(255, 0, 0));
        etiPrecioError.setText("Introduce un precio válido");
        panelCrear.add(etiPrecioError, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        etiAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCrear.add(etiAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 90));

        btnCargarImg.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnCargarImg.setText("Cargar imagen");
        panelCrear.add(btnCargarImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, -1));

        etiEmail1.setText("Descripción:");
        panelCrear.add(etiEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));
        panelCrear.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 130, -1));
        panelCrear.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        panelCrear.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 130, 70));

        errorRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelCrear.add(errorRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 22, 20));

        errorNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelCrear.add(errorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 22, 20));

        errorCompanyia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelCrear.add(errorCompanyia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 22, 20));

        errorTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelCrear.add(errorTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 22, 20));

        errorDescripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelCrear.add(errorDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 22, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(panelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(panelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAceptar;
    public static javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnCargarImg;
    public static javax.swing.JButton btnNuevo;
    public static javax.swing.JButton btnOK;
    public static javax.swing.JButton btnVolver;
    public static javax.swing.JButton errorCompanyia;
    public static javax.swing.JButton errorDescripcion;
    public static javax.swing.JButton errorNombre;
    public static javax.swing.JButton errorPrecio;
    public static javax.swing.JButton errorRef;
    public static javax.swing.JButton errorTipo;
    public static javax.swing.JLabel etiAvatar;
    private javax.swing.JLabel etiEmail;
    private javax.swing.JLabel etiEmail1;
    public static javax.swing.JLabel etiGuardado;
    public static javax.swing.JLabel etiPrecioError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel panelCrear;
    public static javax.swing.JTextField txtCompanyia;
    public static javax.swing.JTextArea txtDescripcion;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtPrecio;
    public static javax.swing.JTextField txtRef;
    public static javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
