/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal_josegramage.Modulos.Inicio.Vista;

/**
 *
 * @author Joso
 */
public class Vtna_Config extends javax.swing.JFrame {

    public Vtna_Config() {
        
        initComponents();
     
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoApariencia = new javax.swing.ButtonGroup();
        grupoMoneda = new javax.swing.ButtonGroup();
        grupoFecha = new javax.swing.ButtonGroup();
        panelConfig = new javax.swing.JPanel();
        moneda = new javax.swing.JPanel();
        euro = new javax.swing.JRadioButton();
        dolar = new javax.swing.JRadioButton();
        libra = new javax.swing.JRadioButton();
        yen = new javax.swing.JRadioButton();
        btnVolverC = new javax.swing.JButton();
        apariencia = new javax.swing.JPanel();
        apariencia2 = new javax.swing.JRadioButton();
        apariencia3 = new javax.swing.JRadioButton();
        apariencia1 = new javax.swing.JRadioButton();
        formatoFecha = new javax.swing.JPanel();
        fecha1 = new javax.swing.JRadioButton();
        fecha2 = new javax.swing.JRadioButton();
        fecha3 = new javax.swing.JRadioButton();
        fecha4 = new javax.swing.JRadioButton();
        fecha6 = new javax.swing.JRadioButton();
        fecha5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moneda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Moneda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        grupoMoneda.add(euro);
        euro.setSelected(true);
        euro.setText("Euro €");

        grupoMoneda.add(dolar);
        dolar.setText("Dolar $");

        grupoMoneda.add(libra);
        libra.setText("Libra £");

        grupoMoneda.add(yen);
        yen.setText("Yen ¥");

        javax.swing.GroupLayout monedaLayout = new javax.swing.GroupLayout(moneda);
        moneda.setLayout(monedaLayout);
        monedaLayout.setHorizontalGroup(
            monedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(monedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(euro)
                    .addComponent(dolar)
                    .addComponent(libra)
                    .addComponent(yen))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        monedaLayout.setVerticalGroup(
            monedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(euro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dolar)
                .addGap(3, 3, 3)
                .addComponent(libra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yen)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnVolverC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolverC.setText("VOLVER");

        apariencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apariencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        grupoApariencia.add(apariencia2);
        apariencia2.setText("Metal");

        grupoApariencia.add(apariencia3);
        apariencia3.setText("Nimbus");

        grupoApariencia.add(apariencia1);
        apariencia1.setSelected(true);
        apariencia1.setText("GTK Windows");

        javax.swing.GroupLayout aparienciaLayout = new javax.swing.GroupLayout(apariencia);
        apariencia.setLayout(aparienciaLayout);
        aparienciaLayout.setHorizontalGroup(
            aparienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aparienciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aparienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apariencia3)
                    .addComponent(apariencia1)
                    .addComponent(apariencia2))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        aparienciaLayout.setVerticalGroup(
            aparienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aparienciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apariencia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apariencia2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(apariencia3)
                .addGap(15, 15, 15))
        );

        formatoFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formato fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        grupoFecha.add(fecha1);
        fecha1.setSelected(true);
        fecha1.setText("dd/mm/yyyy");

        grupoFecha.add(fecha2);
        fecha2.setText("mm/dd/yyyy");

        grupoFecha.add(fecha3);
        fecha3.setText("dd-mm-yyyy");

        grupoFecha.add(fecha4);
        fecha4.setText("mm-dd-yyyy");

        grupoFecha.add(fecha6);
        fecha6.setText("mm.dd.yyyy");

        grupoFecha.add(fecha5);
        fecha5.setText("dd.mm.yyyy");

        javax.swing.GroupLayout formatoFechaLayout = new javax.swing.GroupLayout(formatoFecha);
        formatoFecha.setLayout(formatoFechaLayout);
        formatoFechaLayout.setHorizontalGroup(
            formatoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formatoFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formatoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha1)
                    .addComponent(fecha2)
                    .addComponent(fecha3)
                    .addComponent(fecha4)
                    .addComponent(fecha6)
                    .addComponent(fecha5))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        formatoFechaLayout.setVerticalGroup(
            formatoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formatoFechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fecha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha3)
                .addGap(3, 3, 3)
                .addComponent(fecha4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fecha5)
                .addGap(3, 3, 3)
                .addComponent(fecha6))
        );

        javax.swing.GroupLayout panelConfigLayout = new javax.swing.GroupLayout(panelConfig);
        panelConfig.setLayout(panelConfigLayout);
        panelConfigLayout.setHorizontalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigLayout.createSequentialGroup()
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnVolverC))
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConfigLayout.createSequentialGroup()
                                .addComponent(moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(formatoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(apariencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        panelConfigLayout.setVerticalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfigLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formatoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addComponent(moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(apariencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnVolverC)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel apariencia;
    public static javax.swing.JRadioButton apariencia1;
    public static javax.swing.JRadioButton apariencia2;
    public static javax.swing.JRadioButton apariencia3;
    public static javax.swing.JButton btnVolverC;
    public static javax.swing.JRadioButton dolar;
    public static javax.swing.JRadioButton euro;
    public static javax.swing.JRadioButton fecha1;
    public static javax.swing.JRadioButton fecha2;
    public static javax.swing.JRadioButton fecha3;
    public static javax.swing.JRadioButton fecha4;
    public static javax.swing.JRadioButton fecha5;
    public static javax.swing.JRadioButton fecha6;
    public static javax.swing.JPanel formatoFecha;
    private javax.swing.ButtonGroup grupoApariencia;
    private javax.swing.ButtonGroup grupoFecha;
    private javax.swing.ButtonGroup grupoMoneda;
    public static javax.swing.JRadioButton libra;
    public static javax.swing.JPanel moneda;
    public static javax.swing.JPanel panelConfig;
    public static javax.swing.JRadioButton yen;
    // End of variables declaration//GEN-END:variables
}
