/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal_josegramage.Modulos.Clientes.Vista;


/**
 *
 * @author Joso
 */
public class Vtna_cli_Modif extends javax.swing.JFrame {

    public Vtna_cli_Modif() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModif = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etiNombreErrorM = new javax.swing.JLabel();
        etiApellidoErrorM = new javax.swing.JLabel();
        etiTelefonoErrorM = new javax.swing.JLabel();
        etiEmailM = new javax.swing.JLabel();
        etiEmailErrorM = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        etiAvatarM = new javax.swing.JLabel();
        etiTipoM = new javax.swing.JLabel();
        etiDireccionM = new javax.swing.JLabel();
        etiDireccionErrorM = new javax.swing.JLabel();
        txtNombreM = new javax.swing.JTextField();
        txtApellidosM = new javax.swing.JTextField();
        txtEmailM = new javax.swing.JTextField();
        txtLoginM = new javax.swing.JTextField();
        txtFnacimientoM = new com.toedter.calendar.JDateChooser();
        btnAceptarM = new javax.swing.JButton();
        errorNombreM = new javax.swing.JButton();
        errorApellidosM = new javax.swing.JButton();
        errorTelfM = new javax.swing.JButton();
        errorFnacimientoM = new javax.swing.JButton();
        btnVolverM = new javax.swing.JButton();
        errorEmailM = new javax.swing.JButton();
        btnCambiarImgM = new javax.swing.JButton();
        errorPasswordM = new javax.swing.JButton();
        errorDireccionM = new javax.swing.JButton();
        comboTipoM = new javax.swing.JComboBox();
        txtTelefonoM = new javax.swing.JTextField();
        txtDireccionM = new javax.swing.JTextField();
        errorLoginM = new javax.swing.JButton();
        txtPasswordM = new javax.swing.JPasswordField();

        panelModif.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        panelModif.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setText("Apellidos:");
        panelModif.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel4.setText("Telefono:");
        panelModif.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel5.setText("Fecha de nacimiento:");
        panelModif.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        etiNombreErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiNombreErrorM.setText("Introduce un nombre valido");
        panelModif.add(etiNombreErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        etiApellidoErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiApellidoErrorM.setText("Introduce apellidos validos");
        panelModif.add(etiApellidoErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        etiTelefonoErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiTelefonoErrorM.setText("Introduce un telefono valido");
        panelModif.add(etiTelefonoErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        etiEmailM.setText("Email:");
        panelModif.add(etiEmailM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        etiEmailErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiEmailErrorM.setText("Introduce un email valido");
        panelModif.add(etiEmailErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel3.setText("Login:");
        panelModif.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setText("Password:");
        panelModif.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        etiAvatarM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelModif.add(etiAvatarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 90));

        etiTipoM.setText("Tipo:");
        panelModif.add(etiTipoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        etiDireccionM.setText("Dirección:");
        panelModif.add(etiDireccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        etiDireccionErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiDireccionErrorM.setText("Introduce una direccion valida");
        panelModif.add(etiDireccionErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));
        panelModif.add(txtNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 129, -1));
        panelModif.add(txtApellidosM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 129, -1));
        panelModif.add(txtEmailM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 130, -1));
        panelModif.add(txtLoginM, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, -1));

        txtFnacimientoM.setDateFormatString("dd/MM/yyyy");
        panelModif.add(txtFnacimientoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        btnAceptarM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAceptarM.setText("ACEPTAR");
        panelModif.add(btnAceptarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 100, -1));

        errorNombreM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 22, 20));

        errorApellidosM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorApellidosM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 22, 20));

        errorTelfM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorTelfM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 22, 20));

        errorFnacimientoM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorFnacimientoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 22, 20));

        btnVolverM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolverM.setText("VOLVER");
        panelModif.add(btnVolverM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 100, -1));

        errorEmailM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorEmailM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 22, 20));

        btnCambiarImgM.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnCambiarImgM.setText("cambiar imagen");
        panelModif.add(btnCambiarImgM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 125, 90, -1));

        errorPasswordM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorPasswordM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 20, 20));

        errorDireccionM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorDireccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 22, 20));

        comboTipoM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuario", "Admin" }));
        panelModif.add(comboTipoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));
        panelModif.add(txtTelefonoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 130, -1));
        panelModif.add(txtDireccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, -1));

        errorLoginM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif.add(errorLoginM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 22, 20));
        panelModif.add(txtPasswordM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAceptarM;
    public static javax.swing.JButton btnCambiarImgM;
    public static javax.swing.JButton btnVolverM;
    public static javax.swing.JComboBox comboTipoM;
    public static javax.swing.JButton errorApellidosM;
    public static javax.swing.JButton errorDireccionM;
    public static javax.swing.JButton errorEmailM;
    public static javax.swing.JButton errorFnacimientoM;
    public static javax.swing.JButton errorLoginM;
    public static javax.swing.JButton errorNombreM;
    public static javax.swing.JButton errorPasswordM;
    public static javax.swing.JButton errorTelfM;
    public static javax.swing.JLabel etiApellidoErrorM;
    public static javax.swing.JLabel etiAvatarM;
    public static javax.swing.JLabel etiDireccionErrorM;
    private javax.swing.JLabel etiDireccionM;
    public static javax.swing.JLabel etiEmailErrorM;
    private javax.swing.JLabel etiEmailM;
    public static javax.swing.JLabel etiNombreErrorM;
    public static javax.swing.JLabel etiTelefonoErrorM;
    public static javax.swing.JLabel etiTipoM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel panelModif;
    public static javax.swing.JTextField txtApellidosM;
    public static javax.swing.JTextField txtDireccionM;
    public static javax.swing.JTextField txtEmailM;
    public static com.toedter.calendar.JDateChooser txtFnacimientoM;
    public static javax.swing.JTextField txtLoginM;
    public static javax.swing.JTextField txtNombreM;
    public static javax.swing.JPasswordField txtPasswordM;
    public static javax.swing.JTextField txtTelefonoM;
    // End of variables declaration//GEN-END:variables
}
