/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal_josegramage.Modulos.Clientes.Vista;


/**
 *
 * @author Joso
 */
public class Vtna_cli_MiPerfil extends javax.swing.JFrame {

    public Vtna_cli_MiPerfil() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModif_MP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etiNombreErrorM = new javax.swing.JLabel();
        etiApellidoErrorM = new javax.swing.JLabel();
        etiTelefonoErrorM = new javax.swing.JLabel();
        etiGuardadoM = new javax.swing.JLabel();
        etiEmailM = new javax.swing.JLabel();
        etiEmailErrorM = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        etiAvatarM = new javax.swing.JLabel();
        etiTipoM = new javax.swing.JLabel();
        etiDireccionM = new javax.swing.JLabel();
        etiDireccionErrorM = new javax.swing.JLabel();
        txtNombreMP = new javax.swing.JTextField();
        txtApellidosMP = new javax.swing.JTextField();
        txtEmailMP = new javax.swing.JTextField();
        txtLoginMP = new javax.swing.JTextField();
        txtPasswordMP = new javax.swing.JTextField();
        txtFnacimientoMP = new com.toedter.calendar.JDateChooser();
        btnAceptarM = new javax.swing.JButton();
        errorNombreM = new javax.swing.JButton();
        errorApellidosM = new javax.swing.JButton();
        errorTelfM = new javax.swing.JButton();
        errorFnacimientoM = new javax.swing.JButton();
        btnOKM = new javax.swing.JButton();
        btnVolverM = new javax.swing.JButton();
        errorEmailM = new javax.swing.JButton();
        btnCambiarImgM = new javax.swing.JButton();
        errorPasswordM = new javax.swing.JButton();
        errorDireccionM = new javax.swing.JButton();
        comboTipoMP = new javax.swing.JComboBox();
        txtTelefonoMP = new javax.swing.JTextField();
        txtDireccionMP = new javax.swing.JTextField();
        btnEliminar_MP = new javax.swing.JButton();
        btnSalir_MP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        panelModif_MP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        panelModif_MP.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel2.setText("Apellidos:");
        panelModif_MP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel4.setText("Telefono:");
        panelModif_MP.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel5.setText("Fecha de nacimiento:");
        panelModif_MP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        etiNombreErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiNombreErrorM.setText("Introduce un nombre valido");
        panelModif_MP.add(etiNombreErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        etiApellidoErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiApellidoErrorM.setText("Introduce apellidos validos");
        panelModif_MP.add(etiApellidoErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        etiTelefonoErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiTelefonoErrorM.setText("Introduce un telefono valido");
        panelModif_MP.add(etiTelefonoErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        etiGuardadoM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiGuardadoM.setForeground(new java.awt.Color(0, 204, 102));
        etiGuardadoM.setText("Perfil modificado con éxito");
        panelModif_MP.add(etiGuardadoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        etiEmailM.setText("Email:");
        panelModif_MP.add(etiEmailM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        etiEmailErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiEmailErrorM.setText("Introduce un email valido");
        panelModif_MP.add(etiEmailErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel3.setText("Login:");
        panelModif_MP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel7.setText("Password:");
        panelModif_MP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        etiAvatarM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelModif_MP.add(etiAvatarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, 90));

        etiTipoM.setText("Tipo:");
        panelModif_MP.add(etiTipoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        etiDireccionM.setText("Dirección:");
        panelModif_MP.add(etiDireccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        etiDireccionErrorM.setForeground(new java.awt.Color(255, 0, 0));
        etiDireccionErrorM.setText("Introduce una direccion valida");
        panelModif_MP.add(etiDireccionErrorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));
        panelModif_MP.add(txtNombreMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 129, -1));
        panelModif_MP.add(txtApellidosMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 129, -1));
        panelModif_MP.add(txtEmailMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 130, -1));
        panelModif_MP.add(txtLoginMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, -1));
        panelModif_MP.add(txtPasswordMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 130, -1));

        txtFnacimientoMP.setDateFormatString("dd/MM/yyyy");
        panelModif_MP.add(txtFnacimientoMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        btnAceptarM.setText("Aceptar");
        panelModif_MP.add(btnAceptarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, -1));

        errorNombreM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif_MP.add(errorNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 22, 20));

        errorApellidosM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif_MP.add(errorApellidosM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 22, 20));

        errorTelfM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif_MP.add(errorTelfM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 22, 20));

        errorFnacimientoM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif_MP.add(errorFnacimientoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 22, 20));

        btnOKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/acierto.png"))); // NOI18N
        panelModif_MP.add(btnOKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 30, 30));

        btnVolverM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVolverM.setText("VOLVER");
        panelModif_MP.add(btnVolverM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 100, -1));

        errorEmailM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif_MP.add(errorEmailM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 22, 20));

        btnCambiarImgM.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnCambiarImgM.setText("cambiar imagen");
        panelModif_MP.add(btnCambiarImgM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, -1));

        errorPasswordM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif_MP.add(errorPasswordM, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 20, 20));

        errorDireccionM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal_josegramage/Img/iconos/error.png"))); // NOI18N
        panelModif_MP.add(errorDireccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 22, 20));

        comboTipoMP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuario", "Admin" }));
        panelModif_MP.add(comboTipoMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));
        panelModif_MP.add(txtTelefonoMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 130, -1));
        panelModif_MP.add(txtDireccionMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 130, -1));

        btnEliminar_MP.setText("Eliminar cuenta");
        panelModif_MP.add(btnEliminar_MP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        btnSalir_MP.setText("Salir");
        panelModif_MP.add(btnSalir_MP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mi perfil");
        panelModif_MP.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModif_MP, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelModif_MP, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAceptarM;
    public static javax.swing.JButton btnCambiarImgM;
    public static javax.swing.JButton btnEliminar_MP;
    public static javax.swing.JButton btnOKM;
    public static javax.swing.JButton btnSalir_MP;
    public static javax.swing.JButton btnVolverM;
    public static javax.swing.JComboBox comboTipoMP;
    public static javax.swing.JButton errorApellidosM;
    public static javax.swing.JButton errorDireccionM;
    public static javax.swing.JButton errorEmailM;
    public static javax.swing.JButton errorFnacimientoM;
    public static javax.swing.JButton errorNombreM;
    public static javax.swing.JButton errorPasswordM;
    public static javax.swing.JButton errorTelfM;
    public static javax.swing.JLabel etiApellidoErrorM;
    public static javax.swing.JLabel etiAvatarM;
    public static javax.swing.JLabel etiDireccionErrorM;
    private javax.swing.JLabel etiDireccionM;
    public static javax.swing.JLabel etiEmailErrorM;
    private javax.swing.JLabel etiEmailM;
    public static javax.swing.JLabel etiGuardadoM;
    public static javax.swing.JLabel etiNombreErrorM;
    public static javax.swing.JLabel etiTelefonoErrorM;
    public static javax.swing.JLabel etiTipoM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel panelModif_MP;
    public static javax.swing.JTextField txtApellidosMP;
    public static javax.swing.JTextField txtDireccionMP;
    public static javax.swing.JTextField txtEmailMP;
    public static com.toedter.calendar.JDateChooser txtFnacimientoMP;
    public static javax.swing.JTextField txtLoginMP;
    public static javax.swing.JTextField txtNombreMP;
    public static javax.swing.JTextField txtPasswordMP;
    public static javax.swing.JTextField txtTelefonoMP;
    // End of variables declaration//GEN-END:variables
}
